version: '3'
services:
  slurmjupyter:
<<<<<<< HEAD
        build: ./jupyter
        #image: slurmjupyter
=======
        image: slurmjupyter
>>>>>>> e1ba6427bc6b9d4d93013f6ac96fcfdfcd436e40
        hostname: slurmjupyter
        user: admin
        volumes:
                - shared-vol:/home/admin
        ports:
                - 8888:8888
  slurmmaster:
<<<<<<< HEAD
        build: ./master
        #image: slurmmaster
=======
        image: slurmmaster
>>>>>>> e1ba6427bc6b9d4d93013f6ac96fcfdfcd436e40
        hostname: slurmmaster
        user: admin
        volumes:
                - shared-vol:/home/admin
        environment:
                - SLURM_CPUS_ON_NODE=2
        ports:
                - 6817:6817
                - 6818:6818
                - 6819:6819
  slurmnode1:
<<<<<<< HEAD
        build: ./node
        #image: slurmnode
=======
        image: slurmnode
>>>>>>> e1ba6427bc6b9d4d93013f6ac96fcfdfcd436e40
        hostname: slurmnode1
        user: admin
        volumes:
                - shared-vol:/home/admin
        environment:
                - SLURM_NODENAME=slurmnode1
                - SLURM_CPUS_ON_NODE=2
        links:
                - slurmmaster
  slurmnode2:
<<<<<<< HEAD
        build: ./node
        #image: slurmnode
=======
        image: slurmnode
>>>>>>> e1ba6427bc6b9d4d93013f6ac96fcfdfcd436e40
        hostname: slurmnode2
        user: admin
        volumes:
                - shared-vol:/home/admin
        environment:
                - SLURM_NODENAME=slurmnode2
                - SLURM_CPUS_ON_NODE=2
        links:
                - slurmmaster
  slurmnode3:
<<<<<<< HEAD
        build: ./node
        #image: slurmnode
=======
        image: slurmnode
>>>>>>> e1ba6427bc6b9d4d93013f6ac96fcfdfcd436e40
        hostname: slurmnode3
        user: admin
        volumes:
                - shared-vol:/home/admin
        environment:
                - SLURM_NODENAME=slurmnode3
                - SLURM_CPUS_ON_NODE=2
        links:
                - slurmmaster
volumes:
        shared-vol:

